apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::349589880339:role/eksctl-udacity-api-test-nodegroup-NodeInstanceRole-5JSLXWBCP9L8
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-07T00:38:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "845"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ebe3cf2a-600b-11ea-aa53-02acd715fa19
